### ISSUE TITLE
Integrate a Sidebar. 

### ISSUE THREAD

**Issue by 100sarthak100** [100sarthak100/GreenFactor-Calulator-And-Data-Visualizer#1]

**Comment by MonarthS** [comment]
Can you provide description?

**Comment by 100sarthak100** [comment]
This app uses the MERN stack. To start the project you need to do -
// For Client-side ->
`
cd client
npm install
npm start
`
- This will open a browser window, something like 'http://localhost:3000' (This is the frontend of the app)

// For Server side -> (in new terminal)
`
cd server
npm install
npm start (or nodemon app)
`

- This will start the Nodejs server

I have integrated the header and the Main Data chart for visualization. You have to integrate a sidebar, with a link to Home and other tabs. 
Also when you open the frontend, it may not (as shown in the provided image) work, as the data is retrieved from the MongoDB database. You can make an account there. After you made the account, you'll receive a URL. Then make a `.env` file and paste it there. Then import it in the code `using process.env()`.
But adding data is not important, as only a sidebar and a footer are to be added.

![MERN](https://user-images.githubusercontent.com/35603506/94987751-49fce880-0586-11eb-911e-48ffeabe252e.PNG)
![Main](https://user-images.githubusercontent.com/35603506/94987754-4cf7d900-0586-11eb-9d95-42f50a49b18d.PNG)
![MongoDB](https://user-images.githubusercontent.com/35603506/94987928-66e5eb80-0587-11eb-9ec8-f09c43c36782.PNG)

**Comment by MonarthS** [comment]
@100sarthak100 are you looking for [this](https://ibb.co/C6mMrD4)?

**Comment by 100sarthak100** [comment]
Yeah, that's exactly what i need

**Comment by 100sarthak100** [comment]
Do you want me to assign it to you?

**Comment by MonarthS** [comment]
Yes, then I'll add PR.

**Comment by MonarthS** [comment]
@100sarthak100 can you check [#4](https://github.com/100sarthak100/GreenFactor-Calulator-And-Data-Visualizer/pull/4)?

**Comment by 100sarthak100** [comment]
I have added the topic as 'hacktoberfest' and a 'hacktoberfest-accepted' as a tag as stated. Check if it works now

**Comment by MonarthS** [comment]
You can check the PR too, if it is ok then you can merge it.

**Comment by 100sarthak100** [comment]
yeah, I am checking the PR if it works then I'll merge it.

**Comment by 100sarthak100** [comment]
Your PR is accepted. Thank you.
