### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by 100sarthak100** [100sarthak100/GreenFactor-Calulator-And-Data-Visualizer#3]

**Comment by ArturLavrov** [comment]
Hi! Could you please assign this one to me?

**Comment by 100sarthak100** [comment]
Yeah sure,
- Add a CONTRIBUTING.md file with contribution guidelines.

**Comment by 100sarthak100** [comment]
Your PR is approved. Thank you for your contribution.
